-- Safe launch RLS hardening.
-- This removes Supabase "RLS disabled" warnings for app-owned public tables.
-- Backend service-role access is unaffected, so existing API features keep working.

ALTER TABLE IF EXISTS users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS personality_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS personality_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS personality_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS memory_vectors ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS usage_tracking ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS daily_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS push_device_tokens ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS life_coach_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS program_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_program_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_daily_completions ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS referral_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS referral_events ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS growth_circles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS circle_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS circle_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS circle_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS circle_activity ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS motivation_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS motivation_card_shares ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS twin_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS twin_match_shares ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS streak_freeze_purchases ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS emotional_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS emotional_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS metric_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_engagement ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS daily_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS behavioral_triggers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_profiles ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS user_activity_patterns ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS proactive_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS shared_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS memory_anniversaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_streaks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS life_context ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS relationship_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS relationship_growth_metrics ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS message_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS conversation_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS topic_cache ENABLE ROW LEVEL SECURITY;
